access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://kavindulakshanperera12:NqvhFwacQMN5atdQ@cluster02.he6otom.mongodb.net/gym?retryWrites=true&w=majority&appName=Cluster02
logging:
  level:
    org.springframework.security: DEBUG